### ISSUE TITLE
Flaky race condition

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/ddht#133]
## What was wrong?

This has been occuring intermittently in the tests

```
DEBUG    async_service.Manager:trio.py:141 <Manager[Network] flags=SRCfe>: _handle_cancelled triggering task cancellation
DEBUG    async_service.Manager:trio.py:141 <Manager[Client] flags=SRCfe>: _handle_cancelled triggering task cancellation
DEBUG    async_service.Manager:trio.py:141 <Manager[Dispatcher] flags=SRCfe>: _handle_cancelled triggering task cancellation
ERROR    async_service.Manager:base.py:346 <Manager[Network] flags=SRCfe>: task _serve_find_nodes[daemon=True] exited with error:
Traceback (most recent call last):
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/async_service/base.py", line 324, in _run_and_manage_task
    await task.run()
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/async_service/trio.py", line 76, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/piper/projects/ddht/ddht/v5_1/network.py", line 469, in _serve_find_nodes
    await self.client.send_found_nodes(
  File "/home/piper/projects/ddht/ddht/v5_1/client.py", line 244, in send_found_nodes
    await self.dispatcher.send_message(message)
  File "/home/piper/projects/ddht/ddht/v5_1/dispatcher.py", line 355, in send_message
    await self._outbound_message_send_channel.send(message)
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/trio/_channel.py", line 161, in send
    self.send_nowait(value)
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/trio/_core/_ki.py", line 160, in wrapper
    return fn(*args, **kwargs)
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/trio/_channel.py", line 141, in send_nowait
    raise trio.BrokenResourceError
trio.BrokenResourceError
```

Diagnosis isn't definitive, but I'm pretty sure what we're seeing here is a race condition in the long running background processes that is occuring during shutdown.

## How can it be fixed?

Not entirely sure.

**Comment by pipermerriam** [comment]
Incomplete solution for this is some sort of error handling to allow this to fail silently *if* we can detect that we're in the process of shutting down.
