### ISSUE TITLE
Strange crash with EndOfChannel and trio.TooSlowError

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/ddht#220]
## What happened

Client crashed with the following error.  It's a little confusing because it looks like the `trio.TooSlowError` should have been handled...

```
   ERROR  2020-11-20 17:09:59,797  async_service.Manager  <Manager[Network] flags=SRcfe>: task _manage_routing_table[daemon=True] exited with error:
Traceback (most recent call last):
  File "/home/piper/projects/ddht/ddht/v5_1/dispatcher.py", line 387, in subscribe_request
    yield receive_channel
  File "/home/piper/projects/ddht/ddht/v5_1/client.py", line 379, in find_nodes
    head_response = await subscription.receive()
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/trio/_channel.py", line 294, in receive
    return await trio.lowlevel.wait_task_rescheduled(abort_fn)
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/trio/_core/_traps.py", line 166, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/outcome/_sync.py", line 111, in unwrap
    raise captured_error
trio.EndOfChannel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/async_service/base.py", line 324, in _run_and_manage_task
    await task.run()
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/async_service/trio.py", line 76, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/piper/projects/ddht/ddht/v5_1/network.py", line 589, in _manage_routing_table
    nursery.start_soon(_probe_network, random_node_id)
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/home/piper/projects/ddht/ddht/v5_1/network.py", line 555, in _probe_network
    found_enrs = await self.recursive_find_nodes(target_node_id)
  File "/home/piper/projects/ddht/ddht/v5_1/network.py", line 440, in recursive_find_nodes
    return await common_recursive_find_nodes(self, target)
  File "/home/piper/projects/ddht/ddht/v5_1/network.py", line 201, in common_recursive_find_nodes
    nursery.cancel_scope.cancel()
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/home/piper/projects/ddht/ddht/v5_1/network.py", line 181, in worker
    await adaptive_timeout(*tasks, threshold=1, variance=2.0)
  File "/home/piper/projects/ddht/ddht/_utils.py", line 215, in adaptive_timeout
    nursery.cancel_scope.cancel()
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/home/piper/projects/ddht/ddht/_utils.py", line 185, in task_wrapper
    await task_fn(*args)
  File "/home/piper/projects/ddht/ddht/v5_1/network.py", line 139, in do_lookup
    found_enrs = await network.find_nodes(node_id, distance)
  File "/home/piper/projects/ddht/ddht/v5_1/network.py", line 354, in find_nodes
    responses = await self.client.find_nodes(
  File "/home/piper/projects/ddht/ddht/v5_1/client.py", line 395, in find_nodes
    return responses
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/piper/projects/ddht/ddht/v5_1/dispatcher.py", line 392, in subscribe_request
    nursery.cancel_scope.cancel()
  File "/home/piper/python-environments/ddht/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/home/piper/projects/ddht/ddht/v5_1/dispatcher.py", line 390, in subscribe_request
    raise trio.TooSlowError from err
trio.TooSlowError
```

## How to fix

:shrug:

**Comment by pipermerriam** [comment]
Maybe still a problem

```
  File "/root/env/lib/python3.8/site-packages/async_service/base.py", line 324, in _run_and_manage_task
    await task.run()
  File "/root/env/lib/python3.8/site-packages/async_service/base.py", line 169, in run
    await self.child_manager.run()
  File "/root/env/lib/python3.8/site-packages/async_service/trio.py", line 205, in run
    raise trio.MultiError(
  File "/root/env/lib/python3.8/site-packages/async_service/base.py", line 324, in _run_and_manage_task
    await task.run()
  File "/root/env/lib/python3.8/site-packages/async_service/trio.py", line 76, in run
    await self._async_fn(*self._async_fn_args)
  File "/root/env/lib/python3.8/site-packages/ddht/v5_1/network.py", line 591, in _manage_routing_table
    nursery.start_soon(_probe_network, target_node_id)
  File "/root/env/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/root/env/lib/python3.8/site-packages/ddht/v5_1/network.py", line 561, in _probe_network
    found_enrs = await self.recursive_find_nodes(target_node_id)
  File "/root/env/lib/python3.8/site-packages/ddht/v5_1/network.py", line 446, in recursive_find_nodes
    return await common_recursive_find_nodes(self, target)
  File "/root/env/lib/python3.8/site-packages/ddht/v5_1/network.py", line 207, in common_recursive_find_nodes
    nursery.cancel_scope.cancel()
  File "/root/env/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/root/env/lib/python3.8/site-packages/ddht/v5_1/network.py", line 183, in worker
    await adaptive_timeout(*tasks, threshold=1, variance=2.0)
  File "/root/env/lib/python3.8/site-packages/ddht/_utils.py", line 265, in adaptive_timeout
    nursery.cancel_scope.cancel()
  File "/root/env/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/root/env/lib/python3.8/site-packages/ddht/_utils.py", line 234, in task_wrapper
    await task_fn(*args)
  File "/root/env/lib/python3.8/site-packages/ddht/v5_1/network.py", line 139, in do_lookup
    found_enrs = await network.find_nodes(node_id, distance)
  File "/root/env/lib/python3.8/site-packages/ddht/v5_1/network.py", line 360, in find_nodes
    responses = await self.client.find_nodes(
  File "/root/env/lib/python3.8/site-packages/ddht/v5_1/client.py", line 395, in find_nodes
    return responses
  File "/root/env/lib/python3.8/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/root/env/lib/python3.8/site-packages/ddht/v5_1/dispatcher.py", line 392, in subscribe_request
    nursery.cancel_scope.cancel()
  File "/root/env/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/root/env/lib/python3.8/site-packages/ddht/v5_1/dispatcher.py", line 390, in subscribe_request
    raise trio.TooSlowError from err
trio.TooSlowError
```

**Comment by pipermerriam** [comment]
This is very confusing because this line is wrapped in exception handling for `trio.TooSlowError`..

```
 File "/root/env/lib/python3.8/site-packages/ddht/v5_1/network.py", line 139, in do_lookup
    found_enrs = await network.find_nodes(node_id, distance)
```

So it's unclear to me why that exception isn't being handled.
