### ISSUE TITLE
Crash from `trio.BrokenResourceError`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/ddht#265]
## What was wrong?

```
ERROR    async_service.Manager:base.py:346 <Manager[Network] flags=SRCfe>: task Client[daemon=True] exited with error: 
Traceback (most recent call last):
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/async_service/base.py", line 324, in _run_and_manage_task
    await task.run()
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/async_service/base.py", line 169, in run
    await self.child_manager.run()
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/async_service/trio.py", line 205, in run
    raise trio.MultiError(
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/async_service/base.py", line 324, in _run_and_manage_task
    await task.run()
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/async_service/base.py", line 169, in run
    await self.child_manager.run()
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/async_service/trio.py", line 205, in run
    raise trio.MultiError(
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/async_service/base.py", line 324, in _run_and_manage_task
    await task.run()
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/async_service/trio.py", line 76, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/circleci/repo/ddht/v5_1/dispatcher.py", line 177, in _handle_inbound_envelopes
    await session.handle_inbound_envelope(envelope)
  File "/home/circleci/repo/ddht/v5_1/session.py", line 601, in handle_inbound_envelope
    await self._send_handshake_response(
  File "/home/circleci/repo/ddht/v5_1/session.py", line 642, in _send_handshake_response
    await self._outbound_envelope_send_channel.send(envelope)
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/trio/_channel.py", line 161, in send
    self.send_nowait(value)
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/trio/_core/_ki.py", line 160, in wrapper
    return fn(*args, **kwargs)
  File "/home/circleci/repo/.tox/py38-core/lib/python3.8/site-packages/trio/_channel.py", line 141, in send_nowait
    raise trio.BrokenResourceError
trio.BrokenResourceError
```

## How can it be fixed?

handle the exception

**Comment by pipermerriam** [comment]
Looks like this is a little less straight forward.  Currently the `EnvelopeEncoder` is a child of the `Client`.  The `Dispatcher` is also a child of the client, which means that they shut down concurrently, allowing the `EnvelopeEncoder` to shut down before the `Dispatcher`, and that means that the dispatcher can end up trying to send information over a closed channel.

We need to change the service hierarchy such that the `Dispatcher` is guaranteed to shut down before the `EnvelopeEncoder`
